version: "3.8"

services:
  shopping-inbox-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: shopping-inbox-server
    restart: always
    volumes:
      - ./server/data/db.json:/app/data/db.json
    ports:
      - 4200:4200
    container_name: server
    command: npm start

  shopping-inbox-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    image: shopping-inbox-client
    volumes:
      - ./client:/app/client
    depends_on:
      - shopping-inbox-server
    ports:
      - 3000:3000
    container_name: client
    command: npm run build
