version: "3.8"

services:
  json-server:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./data/db.json:/app/data/db.json
    ports:
      - 9000:9000
    image: shopping-inbox-server
    container_name: server
    command: npm run server

  shopping:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: shopping-inbox-client
    container_name: client
    command: npm start
